# Darkademia Color Scheme

selection_foreground #080808
selection_background #ffffff

foreground #ffffff
background #080808

color0   #080808
color1   #5b321e
color2   #4a4d32
color3   #80581b
color4   #242a28
color5   #311e20
color6   #927d5e
color7   #e3ded1

color8   #262626
color9   #753f26
color10  #626642
color11  #996820
color12  #39423f
color13  #492d2f
color14  #aa916d
color15  #ffffff

active_tab_foreground #ffffff
active_tab_background #080808
inactive_tab_foreground #e3ded1
inactive_tab_background #080808
